apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "db-databasetest-1772153459572"
  namespace: "client-apps"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "db-databasetest-1772153459572"
  template:
    metadata:
      labels:
        app: "db-databasetest-1772153459572"
    spec:
      containers:
      - name: "db-databasetest-1772153459572"
        image: "mysql:8.0"
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_DATABASE"
          value: "databasetest"
        - name: "MYSQL_USER"
          value: "usernametest"
        - name: "MYSQL_PASSWORD"
          value: "password@12test@"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "password@12test@"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "db-databasetest-1772153459572-svc"
  namespace: "client-apps"
spec:
  type: "ClusterIP"
  selector:
    app: "db-databasetest-1772153459572"
  ports:
  - port: 3306
    targetPort: 3306
